# Generated by Django 3.2.5 on 2021-10-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='birthM',
        ),
    ]
