# Generated by Django 3.2.5 on 2021-10-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_userdata_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='petfood',
            field=models.TextField(null=True),
        ),
    ]
