# Generated by Django 3.2.5 on 2021-10-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userdata_petfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='petfood',
            field=models.TextField(default=''),
        ),
    ]
